#pragma once


enum PacketID
{
	MSG_GASVR_REGTO_PROXY_REQ,
	MSG_BROAD_MESSAGE_NOTIFY,
	MSG_ENTER_SCENE_REQ,
	MSG_ROLE_LOGIN_ACK,
	MSG_ROLE_LOGOUT_REQ,
	MSG_ROLE_OTHER_LOGIN_NTY,

	MSG_ROLE_LIST_REQ,
	MSG_ROLE_CREATE_REQ,
	MSG_ROLE_DELETE_REQ,
	MSG_ROLE_LOGIN_REQ,
	MSG_ROLE_RECONNECT_REQ
};